name: Deploy to Coolify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deployment
        run: |
          curl -X POST "https://s1.devonauts.co.uk/api/v1/deploy?uuid=${{ secrets.PLAYGROUND_DEPLOY_UUID }}&force=false" \
            -H "Authorization: Bearer ${{ secrets.PLAYGROUND_TOKEN }}"
